name: Create Deployment Pull Request

on:
   workflow_dispatch:

jobs:
   create-pr:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Code
           uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - name: Backup Main  Branch Code
           uses: actions/upload-artifact@v4
           with:
              name: Main_Branch_Local_Backup
              path: .

         - name: Create Pull Request and Print URL
           env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
           run: |
              echo "================================================================================================"
              echo " Creating process for dynaically PR"
              echo "================================================================================================"
              #Store  PR url in one variable
              PR_URL=$(gh pr create \
                 --base main \
                 --head "${{ github.ref_name}}" \
                 --title "Deploy ${{ github.ref_name}} to main" \
                 --body "This Pull reuest was automatically created by GHA from the current branch. Click the link below to merge.")

              echo ""
              echo "================================================================================================"
              echo " PR Created Successfully."
              echo "Click on this url and open it into new tab and merge it."
              echo "$PR_URL"
              echo "================================================================================================"

              
