name: Create Deployment Pull Request

on:
   workflow_dispatch:

jobs:
   create-pr:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Code
           uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - name: Create Pull Request Dynamically
           env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
           run: |
              #Automatically select the branch
              gh pr create \
                 --base main \
                 --head "${{ github.ref_name}}" \
                 --title "Deploy ${{ github.ref_name}} to main" \
                 --body "This Pull reuest was automatically created by GHA from the current branch."
              
