name: Run Python via Docker Container

on:
   push: 
   workflow_dispatch:

jobs:
   docker-run:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Code
           uses: actions/checkout@v4
           
         - name: Run Script Inside Docker Python Image
           run: |
              docker run --rm -v ${{github.workspace}}:/app -w /app python:3.10-sim python my_program.py
